//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.NguyenLieuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NguyenLieuService.INguyenLieuServices")]
    public interface INguyenLieuServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/DoWork", ReplyAction="http://tempuri.org/INguyenLieuServices/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/DoWork", ReplyAction="http://tempuri.org/INguyenLieuServices/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/getDSNL", ReplyAction="http://tempuri.org/INguyenLieuServices/getDSNLResponse")]
        System.Data.DataTable getDSNL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/getDSNL", ReplyAction="http://tempuri.org/INguyenLieuServices/getDSNLResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDSNLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/getDSNL_theoma", ReplyAction="http://tempuri.org/INguyenLieuServices/getDSNL_theomaResponse")]
        System.Data.DataTable getDSNL_theoma(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/getDSNL_theoma", ReplyAction="http://tempuri.org/INguyenLieuServices/getDSNL_theomaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDSNL_theomaAsync(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/kiemTraNL", ReplyAction="http://tempuri.org/INguyenLieuServices/kiemTraNLResponse")]
        bool kiemTraNL(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/kiemTraNL", ReplyAction="http://tempuri.org/INguyenLieuServices/kiemTraNLResponse")]
        System.Threading.Tasks.Task<bool> kiemTraNLAsync(string maNL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/ThemNL", ReplyAction="http://tempuri.org/INguyenLieuServices/ThemNLResponse")]
        bool ThemNL(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/ThemNL", ReplyAction="http://tempuri.org/INguyenLieuServices/ThemNLResponse")]
        System.Threading.Tasks.Task<bool> ThemNLAsync(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/SuaNL", ReplyAction="http://tempuri.org/INguyenLieuServices/SuaNLResponse")]
        bool SuaNL(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/SuaNL", ReplyAction="http://tempuri.org/INguyenLieuServices/SuaNLResponse")]
        System.Threading.Tasks.Task<bool> SuaNLAsync(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/XoaNL", ReplyAction="http://tempuri.org/INguyenLieuServices/XoaNLResponse")]
        bool XoaNL(DTO_QLCP.NguyenLieu nl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguyenLieuServices/XoaNL", ReplyAction="http://tempuri.org/INguyenLieuServices/XoaNLResponse")]
        System.Threading.Tasks.Task<bool> XoaNLAsync(DTO_QLCP.NguyenLieu nl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INguyenLieuServicesChannel : QuanLiCaPhe.NguyenLieuService.INguyenLieuServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NguyenLieuServicesClient : System.ServiceModel.ClientBase<QuanLiCaPhe.NguyenLieuService.INguyenLieuServices>, QuanLiCaPhe.NguyenLieuService.INguyenLieuServices {
        
        public NguyenLieuServicesClient() {
        }
        
        public NguyenLieuServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NguyenLieuServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguyenLieuServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguyenLieuServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable getDSNL() {
            return base.Channel.getDSNL();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDSNLAsync() {
            return base.Channel.getDSNLAsync();
        }
        
        public System.Data.DataTable getDSNL_theoma(string maNL) {
            return base.Channel.getDSNL_theoma(maNL);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDSNL_theomaAsync(string maNL) {
            return base.Channel.getDSNL_theomaAsync(maNL);
        }
        
        public bool kiemTraNL(string maNL) {
            return base.Channel.kiemTraNL(maNL);
        }
        
        public System.Threading.Tasks.Task<bool> kiemTraNLAsync(string maNL) {
            return base.Channel.kiemTraNLAsync(maNL);
        }
        
        public bool ThemNL(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.ThemNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> ThemNLAsync(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.ThemNLAsync(nl);
        }
        
        public bool SuaNL(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.SuaNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> SuaNLAsync(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.SuaNLAsync(nl);
        }
        
        public bool XoaNL(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.XoaNL(nl);
        }
        
        public System.Threading.Tasks.Task<bool> XoaNLAsync(DTO_QLCP.NguyenLieu nl) {
            return base.Channel.XoaNLAsync(nl);
        }
    }
}
