//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCaPhe.NhanVienService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NhanVienService.INhanVienService")]
    public interface INhanVienService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/DoWork", ReplyAction="http://tempuri.org/INhanVienService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/DoWork", ReplyAction="http://tempuri.org/INhanVienService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/ThemNV", ReplyAction="http://tempuri.org/INhanVienService/ThemNVResponse")]
        bool ThemNV(DTO_QLCP.NhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/ThemNV", ReplyAction="http://tempuri.org/INhanVienService/ThemNVResponse")]
        System.Threading.Tasks.Task<bool> ThemNVAsync(DTO_QLCP.NhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/getDSNV", ReplyAction="http://tempuri.org/INhanVienService/getDSNVResponse")]
        System.Data.DataTable getDSNV();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/getDSNV", ReplyAction="http://tempuri.org/INhanVienService/getDSNVResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDSNVAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/getDSNV_theoma", ReplyAction="http://tempuri.org/INhanVienService/getDSNV_theomaResponse")]
        System.Data.DataTable getDSNV_theoma(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/getDSNV_theoma", ReplyAction="http://tempuri.org/INhanVienService/getDSNV_theomaResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getDSNV_theomaAsync(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/kiemTraNhanVien", ReplyAction="http://tempuri.org/INhanVienService/kiemTraNhanVienResponse")]
        bool kiemTraNhanVien(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/kiemTraNhanVien", ReplyAction="http://tempuri.org/INhanVienService/kiemTraNhanVienResponse")]
        System.Threading.Tasks.Task<bool> kiemTraNhanVienAsync(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/SuaNV", ReplyAction="http://tempuri.org/INhanVienService/SuaNVResponse")]
        bool SuaNV(DTO_QLCP.NhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/SuaNV", ReplyAction="http://tempuri.org/INhanVienService/SuaNVResponse")]
        System.Threading.Tasks.Task<bool> SuaNVAsync(DTO_QLCP.NhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/XoaNV", ReplyAction="http://tempuri.org/INhanVienService/XoaNVResponse")]
        bool XoaNV(DTO_QLCP.NhanVien nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INhanVienService/XoaNV", ReplyAction="http://tempuri.org/INhanVienService/XoaNVResponse")]
        System.Threading.Tasks.Task<bool> XoaNVAsync(DTO_QLCP.NhanVien nv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INhanVienServiceChannel : QuanLiCaPhe.NhanVienService.INhanVienService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NhanVienServiceClient : System.ServiceModel.ClientBase<QuanLiCaPhe.NhanVienService.INhanVienService>, QuanLiCaPhe.NhanVienService.INhanVienService {
        
        public NhanVienServiceClient() {
        }
        
        public NhanVienServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NhanVienServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanVienServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanVienServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public bool ThemNV(DTO_QLCP.NhanVien nv) {
            return base.Channel.ThemNV(nv);
        }
        
        public System.Threading.Tasks.Task<bool> ThemNVAsync(DTO_QLCP.NhanVien nv) {
            return base.Channel.ThemNVAsync(nv);
        }
        
        public System.Data.DataTable getDSNV() {
            return base.Channel.getDSNV();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDSNVAsync() {
            return base.Channel.getDSNVAsync();
        }
        
        public System.Data.DataTable getDSNV_theoma(string maNV) {
            return base.Channel.getDSNV_theoma(maNV);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getDSNV_theomaAsync(string maNV) {
            return base.Channel.getDSNV_theomaAsync(maNV);
        }
        
        public bool kiemTraNhanVien(string maNV) {
            return base.Channel.kiemTraNhanVien(maNV);
        }
        
        public System.Threading.Tasks.Task<bool> kiemTraNhanVienAsync(string maNV) {
            return base.Channel.kiemTraNhanVienAsync(maNV);
        }
        
        public bool SuaNV(DTO_QLCP.NhanVien nv) {
            return base.Channel.SuaNV(nv);
        }
        
        public System.Threading.Tasks.Task<bool> SuaNVAsync(DTO_QLCP.NhanVien nv) {
            return base.Channel.SuaNVAsync(nv);
        }
        
        public bool XoaNV(DTO_QLCP.NhanVien nv) {
            return base.Channel.XoaNV(nv);
        }
        
        public System.Threading.Tasks.Task<bool> XoaNVAsync(DTO_QLCP.NhanVien nv) {
            return base.Channel.XoaNVAsync(nv);
        }
    }
}
